#ifndef INV_COMPASS_CAL_LIB__H
#define INV_COMPASS_CAL_LIB__H


#ifdef __cplusplus
extern "C" {
#endif

#define INV_COMPASS_STORAGE_SIZE 64

/** Initialize the compass cal library module.
* @param[in] compass_cal - Input pointer for this class
*/
void dmp3_compass_cal_lib_init(void *compass_cal);

/** Run compass cal
* @param[in] compass - raw compass data
* @param[in] compass_prep - compass cal input from DMP
* @param[in] softIron - soft iron matrix
*/
void dmp3_compass_cal_lib_process(int *compass, int compass_prep, int *softIron);

/** Store compass cal output
* @param[out] compass_cal
*/
void dmp3_compass_cal_lib_store_output(void *compass_cal);

/** Sets compass rate
* @param[in] rate
*/
void dmp3_compass_cal_lib_set_compass_rate(short rate);

/** Get calibrated compass data
* @param[in] compass_cal - Input pointer for this class
* @param[out] data - calibrated compass output
*/
void dmp3_compass_cal_lib_get_compass_calibrated(void *compass_cal, int *data);

/** Get compass bias
* @param[in] compass_cal - Input pointer for this class
* @param[out] data - compass bias
*/
void dmp3_compass_cal_lib_get_compass_bias(void *compass_cal, int *data);

/** Get compass accuracy
* @param[in] compass_cal - Input pointer for this class
* returns compass accuracy
*/
int dmp3_compass_cal_lib_get_compass_accuracy(void *compass_cal);

/** Get compass magnetic disturbance to be used for 9-axis
* @param[in] compass_cal - Input pointer for this class
* returns compass magnetic disturbance
*/
short dmp3_compass_cal_lib_get_compass_mag_dis(void *compass_cal);

/** Get fusion data generated by compass cal
* @param[in] compass_cal - Input pointer for this class
* @param[out] data - compass cal fusion data
*/
void dmp3_compass_cal_lib_get_fusion_data(void *compass_cal, int *data);

/** Sets compass bias
* @param[in] compass x,y,z
*/
void dmp3_compass_cal_lib_set_compass_bias(int *compass_bias);

/** Sets compass scale
* @param[in] compass scale
*/
void dmp3_compass_cal_lib_set_scale(int *scale);
#ifdef __cplusplus
}
#endif


#endif // INV_COMPASS_CAL_LIB__H
