python namecodec.py encode com.antutu.ABenchMark>>out.txt
python namecodec.py encode com.qihoo360.mobilesafe.opti>>out.txt
python namecodec.py encode com.qihoo360.mobilesafe.bench>>out.txt
python namecodec.py encode com.glbenchmark.glbenchmark25>>out.txt
python namecodec.py encode com.ludashi.benchmark>>out.txt
python namecodec.py encode com.rightware.tdmm2v10jnifree>>out.txt
python namecodec.py encode com.futuremark.dmandroid.application>>out.txt
python namecodec.py encode com.greenecomputing.linpack>>out.txt
python namecodec.py encode com.tactel.electopia>>out.txt
python namecodec.py encode eu.chainfire.cfbench>>out.txt
python namecodec.py encode com.quicinc.vellamo>>out.txt
python namecodec.py encode com.aurorasoftworks.quadrant.ui.advanced>>out.txt
python namecodec.py encode com.threed.jpct.bench>>out.txt
python namecodec.py encode se.nena.nenamark2>>out.txt
python namecodec.py encode fishnoodle.benchmark>>out.txt
python namecodec.py encode com.google.android.exoplayer.gts>>out.txt
